### ISSUE TITLE
The path does not exist

### ISSUE THREAD

**Issue by paulcsiki** [sylviiu/ezytdl#101]
### Title: 
Error getting info

### Content: 
The path does not exist.

### Stack: 
```js
- at module.exports (C:\Users\paulc\AppData\Local\Programs\ezytdl\resources\app.asar\core\sendNotification.js:24:34)
- at C:\Users\paulc\AppData\Local\Programs\ezytdl\resources\app.asar\util\ytdlp.js:933:13
```

### Below this line, please describe what caused this error.
----
I have tried to queue up a long channel to download and after 10 minutes of UI lack of response I have killed the process. Upon restarting the app, every url that I try to input will result in the error above.

**Comment by sylviiu** [comment]
I'll be honest and say that this isn't the first issue related to path issues the app has had, but I could never figure out exactly what caused it (I've never had this happen to me, on Linux, Mac or Windows).

What version are you currently using?

**Comment by paulcsiki** [comment]
I'm using the latest stable one.

**Comment by paulcsiki** [comment]
I've had my download folder set to H:\dl and creating H:\dl\twitch.tv has solved the issue.

**Comment by sylviiu** [comment]
veery strange, that's still definitely a bug.. i haven't been able to experience this issue (though i've been on nightly builds, so maybe i've patched it a while ago?)

what's even more confusing is that in the source code for 2.4.2, that error stack doesn't point to anything in particular
![image](https://github.com/sylviiu/ezytdl/assets/95180094/c4ab1399-03d0-4a5c-ba39-2cdb8806996e)

i'll go ahead and close this for now since it seems to be resolved (and that i can't actually find anything from the stack??) but if the issue persists with possibly another website, i'll look into that further.
