### ISSUE TITLE
Failing to find ffmpeg deletes downloaded videos on download & convert

### ISSUE THREAD

**Issue by paulcsiki** [sylviiu/ezytdl#104]
If you start an operation that downloads and converts streams and then it fails due to a missing ffmpeg (and probably a failed conversion too) will delete raw videos rather than leaving them there so a retry operation can be completed.

In my case it nuked 50gb of raw videos.

**Comment by sylviiu** [comment]
my jaw dropped, i'm actually so sorry about that.

this issue has long been fixed in nightly builds, but i've been so caught up in life that i haven't been able to put so much time into completing 3.0.0 so that's been pending for 4 months.

i'm working on applying certain patches downstream to make a quick stable hotfix release of the app, but i have no ETA on that one since it's been so long, i have to look back at the long commit history to figure out what patches are necessary

<details>
<summary>as weird as it is to say, with the current state of ezytdl, a much better experience is warranted by switching to nightly / dev builds in settings</summary>

> in the settings menu, scroll down a little bit to find the dev updates option, enable that and save changes
> ![image](https://github.com/sylviiu/ezytdl/assets/95180094/7bacd608-424a-45d7-ab88-a965082bffa3)

> afterwards, at the tray icon, manually perform an update check to download the latest dev build
> ![image](https://github.com/sylviiu/ezytdl/assets/95180094/7901b947-9148-4101-8aba-492ba8c1557b)

</details>

i point out nightly / dev builds, because it has a much better error handler implemented (and actually gives you a menu that shows exactly what went wrong), and it does not delete the video unless you manually prompt it to (which i thought should've been a thing in 2.4.2? it might have been problematic in that build)

**Comment by paulcsiki** [comment]
Great, I'll switch to the latest develop then, this way at least I can also report any bugs I might find. Thank you.
