### ISSUE TITLE
An option to add a Music Key & || BPM to the songs meta data

### ISSUE THREAD

**Issue by Judannn** [sylviiu/ezytdl#113]
This may be well out the scope of this application.
However as a DJ this would be amazing!

(I may even fork and do this myself when I have time)

**Comment by sylviiu** [comment]
I personally really love that idea, but the issue is most platforms / services don't store BPM information, and it would likely be difficult to cross reference with another platform.

*HOWEVER,* [it does look like Spotify's API also offers BPM information on a track](https://developer.spotify.com/documentation/web-api/reference/get-audio-features); if I were to implement something like this, I can tie it in with the existing Spotify integration on the app.

If you know of another platform that easily provides information like this, do let me know!

**Comment by sylviiu** [comment]
Little progress update (sorry for being so late), decided to go with the Spotify route, since that was the easiest to implement since there was already an authorization system implemented for it

Had to implement Spotify searching so I can cross reference with it like the app does with YouTube; should be able to get this done relatively soon :D
![imagen](https://github.com/sylviiu/ezytdl/assets/95180094/5c55c051-c64c-4e3b-a747-5951e7dc2362)

**Comment by sylviiu** [comment]
"working example" :D

https://github.com/sylviiu/ezytdl/assets/95180094/4ddce74b-6b8e-4340-b288-d8c174ec4a1e

this basically cross references any source media with an equivalent found on spotify (if any), and will apply the BPM / key data from that spotify listing!

will try to get this released to the next nightly build tonight :D

**Comment by Judannn** [comment]
Awesome work! Thank you :)
