### ISSUE TITLE
Folder name getting inserted as album metadata

### ISSUE THREAD

**Issue by zcraber** [sylviiu/ezytdl#33]
While downloading multiple Spotify albums at once, instead of the album name, the folder name is getting inserted as metadata.

![image](https://github.com/sylviiu/ezytdl/assets/61133303/26bd4b77-dd97-417f-9935-689ff631c38f)

**Comment by sylviiu** [comment]
man I knew my software in general was unreliable but I didn't know there were THIS many bugs 😭

I'll look into it later on :)

**Comment by zcraber** [comment]
It's not unreliable. For me, it's a very useful app! 😀 Just like the previous bug, this only happens when you download multiple albums.

**Comment by sylviiu** [comment]
boom.

![image](https://github.com/sylviiu/ezytdl/assets/95180094/50923f7d-a12f-482a-9071-a86937ed5f9d)
![image](https://github.com/sylviiu/ezytdl/assets/95180094/029e52dc-5588-4b59-8318-b03a728597b1)

turns out that the code was (for the most part) *already* supposed to be doing this, but i forgot this one line of code.

![image](https://github.com/sylviiu/ezytdl/assets/95180094/eda51128-ac91-4d26-8beb-c1f6a0ebb7fd)
