### ISSUE TITLE
error

### ISSUE THREAD

**Issue by matin774** [sylviiu/ezytdl#69]
### Title: 
Internal error occurred!

### Content: 
{}

TypeError: Cannot read properties of undefined (reading 'items')
    at parse (C:\Users\martijn\AppData\Local\Programs\ezytdl\resources\app.asar\util\platforms\spotify.js:27:79)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

(no stack)

### Stack: 
```js
- at module.exports (C:\Users\martijn\AppData\Local\Programs\ezytdl\resources\app.asar\core\sendNotification.js:9:30)
- at module.exports (C:\Users\martijn\AppData\Local\Programs\ezytdl\resources\app.asar\util\errorHandler.js:8:48)
- at process.<anonymous> (C:\Users\martijn\AppData\Local\Programs\ezytdl\resources\app.asar\index.js:20:125)
- at process.emit (node:events:513:28)
- at emit (node:internal/process/promises:149:20)
- at processPromiseRejections (node:internal/process/promises:294:27)
- at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

### Below this line, please describe what caused this error.
----

**Comment by sylviiu** [comment]
sorry for getting back so late! this issue has been fixed in issue #18, but hasn't been released in a stable release yet

i'm still gearing up towards a 3.0 release in the near future, meaning that this release is only available in the latest nightly version

go to settings, scroll down a bit and enable this option -- don't forget to save :D
![image](https://github.com/sylviiu/ezytdl/assets/95180094/3a10c87f-cc9a-444a-ba1f-eb12e7366229)

then, go to the tray menu and check for updates
![image](https://github.com/sylviiu/ezytdl/assets/95180094/47bca952-6a66-428c-9ecd-2938ae407e87)

it should give you the option to update to the latest nightly version -- this should fix this problem!
