### ISSUE TITLE
The bridge process closed.

### ISSUE THREAD

**Issue by absoluteVendingMachine** [sylviiu/ezytdl#87]
Device: MacBook Pro 2019 (Intel Mac) on macOS Sonoma
Version: 3.0.0-dev.20 (assumedly also happens on older versions)

When opening ezytdl, it will spam a message saying that the bridge process closed. I tried reopening the app and I was on an older version, so I figured maybe that was why it was happening. 

I updated to the latest version of ezytdl (3.0.0-dev.20), but the same issue occurred, so I thought maybe some bad files were left behind and cleaned them with AppCleaner. After this, the issue didn't happen again, until I tried to download a video.

**Comment by sylviiu** [comment]
do you mean dev 209..? that's the latest version of the nightly builds there is -- if not, try updating to that.

please forgive me, I don't use a mac, so I'm going off of what I know here lol

try deleting the pybridge folder in the app data dir (linux: `~/.config/ezytdl/bridge-*`; windows: `%APPDATA%\ezytdl\bridge-*`) and restart the app; this should give you a completely fresh install of the bridge.

**Comment by absoluteVendingMachine** [comment]
> do you mean dev 209..? that's the latest version of the nightly builds there is -- if not, try updating to that.
> 
> please forgive me, I don't use a mac, so I'm going off of what I know here lol
> 
> try deleting the pybridge folder in the app data dir (linux: `~/.config/ezytdl/bridge-*`; windows: `%APPDATA%\ezytdl\bridge-*`) and restart the app; this should give you a completely fresh install of the bridge.

My mistake, yes it's dev 209.

I'm not sure where the pybridge directory is in macOS, but I believe I've found it (screenshot attached) as it yields the same result as you describe, but deleting this still doesn't fix the issue.

<img width="1502" alt="Screenshot 2023-10-19 at 2 35 53 PM" src="https://github.com/sylviiu/ezytdl/assets/113253898/d6e604dd-d941-4a3a-a3cb-370eab11be76">
<img width="987" alt="Screenshot 2023-10-19 at 2 38 34 PM" src="https://github.com/sylviiu/ezytdl/assets/113253898/98313d7f-de38-48a9-835b-c58efed7213a">

**Comment by sylviiu** [comment]
hmm, very very odd. that does seem to be the right location!

can you try [downloading the latest pybridge release](https://github.com/sylviiu/ytdlp-pybridge/releases/tag/96), extracting it manually and placing it in the exact same directory? i'm wondering if this is another unzipping incompatibility that a nightly version had in the past

**Comment by absoluteVendingMachine** [comment]
<img width="372" alt="Screenshot 2023-10-21 at 6 34 44 PM" src="https://github.com/sylviiu/ezytdl/assets/113253898/083d3dbb-5563-418d-a870-09073ce58c81">

Unzipping the latest bridge-darwin folder gives this prompt, and moving it to the trash replicates the error that was happening previously.

**Comment by sylviiu** [comment]
huh.. i'll look more into this; i've never seen that issue before?? likely something to do with the compression

*i finally have a reason to revive my macbook and look for that power cable!*

**Comment by CDotNightHawk** [comment]
I can also say that it is happening on my end as well.

**Comment by sylviiu** [comment]
sorry! haven't actually got around to getting the macbook working -- looking into it right now since i'm also being pressured into looking at it off of github too now 😎

**Comment by CDotNightHawk** [comment]
It fine, also I will let you know I fine you as one of my favorite developers. The app style is one of the best.

**Comment by sylviiu** [comment]
yup, definitely can replicate this on my end. i'll try to get this fixed tonight before next nightly release!

**Comment by absoluteVendingMachine** [comment]
awesome, thanks for confirming

**Comment by sylviiu** [comment]
## i bring some good news!!

the issue has FINALLY been fixed.
![Screen Shot 2023-10-28 at 10 50 36 PM](https://github.com/sylviiu/ezytdl/assets/95180094/7c221b2f-0bbf-412e-a65d-405c27beda9a)
<sub>i'm so sorry for not working on this sooner; i haven't been focusing much on development as of lately but i'm trying to organize my schedule properly so i can get back to this more :D</sub>

there are no new builds for ezytdl with this bug! it was likely due to the compression that 7zip does which somehow made the binaries just unreadable i guess, not sure BUT i switched to the zip command that macOS itself provides and everything seems to work again on my side

**DO NOTE** that because of the nature of the app being single-threaded, it might be difficult to reach the settings page while you're being flooded with those "The bridge process closed" messages; the easiest way for things to just start Working again is by maunally removing the borked bridge files in a terminal by running `rm -rf ~/Library/Application\ Support/ezytdl/bridge-darwin` -- doing this will force the app to download the latest version of the bridge since it has nothing to start :D

i'll close the issue for now since i'm 99% sure the issue has been fixed, BUT if it still has not been fixed for one of you i'll reopen it and debug further!

THANK YOU for being patient with me 💜💜
